# Generated by Django 3.2 on 2021-06-09 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20210603_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='country',
            field=models.CharField(default='asdf', max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='dayBar',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(default='asdf', max_length=2000),
        ),
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='asdf', max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='lastUpdateDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stock',
            name='minuteBar',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stock',
            name='companyName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tabs',
            field=models.JSONField(),
        ),
    ]
