# Generated by Django 3.2 on 2021-06-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20210609_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dayBar',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lastUpdateDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minuteBar',
            field=models.JSONField(),
        ),
    ]
