# Generated by Django 3.2 on 2021-06-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20210609_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AddField(
            model_name='stock',
            name='keyStats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
