# Generated by Django 3.2 on 2021-06-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_auto_20210609_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='keyStats',
            field=models.JSONField(),
        ),
    ]
