# Generated by Django 3.2 on 2021-06-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_alter_stock_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='companyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=100),
        ),
    ]
