# Generated by Django 3.2 on 2021-06-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_auto_20210609_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dayBar',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minuteBar',
            field=models.JSONField(default=list),
        ),
    ]
