# Generated by Django 3.2 on 2021-08-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0011_auto_20210612_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stocks',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stock',
            name='companyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dayBar',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='keyStats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lastUpdateDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minuteBar',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quote',
            field=models.JSONField(default=list),
        ),
    ]
