# Generated by Django 3.2 on 2021-09-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0013_alter_userprofile_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dash',
            field=models.JSONField(default=list),
        ),
    ]
