# Generated by Django 3.2 on 2022-03-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0016_alter_userprofile_dash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dash',
            field=models.JSONField(default=list),
        ),
    ]
