# Generated by Django 3.2 on 2022-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0018_remove_userprofile_dash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dash',
            field=models.JSONField(default=list),
        ),
    ]
