# Generated by Django 3.2 on 2022-03-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0019_userprofile_dash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dash',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stocks',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tabs',
            field=models.JSONField(default=list),
        ),
    ]
